### ISSUE TITLE
Frontend typos and Bugs

### ISSUE THREAD

**Issue by q96exe** [q96exe/ddf#46]
Create Lobby Modal: 

- [x] - "UserName" to "Username"
- [x] - Text | Voice not a RadioButtonGroup, you are able to deselect the buttons

Join Lobby Modal:

- [x] if something is in the input, then you tab out and the placeholder is moved over the input
- [x] "UserName" to "Username"
- [x] Buttons have no margin to modal border

**Comment by GingerFury6** [comment]
All Issues solved.
