### ISSUE TITLE
Change text color for Text | Voice buttons

### ISSUE THREAD

**Issue by q96exe** [q96exe/ddf#49]
**Describe the bug**
Change the color of the buttons text for "Text | Voice" to background color, also if not selected

**To Reproduce**
1. Go to landingpage
2. Click on 'Erstellen'

**Screenshots**
-

**Comment by GingerFury6** [comment]
Finished coloring of SelectButton element inside createLobby Modal. 

Added control focus with tabindex to navigate between input elements with tab key.
